import { useState } from 'react';
import { CheckCircle2, Clock3, Download, XCircle } from 'lucide-react';
import { useExportsQuery } from '../api';

const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:4000/api';
export function Exports() {
  const [page, setPage] = useState(1);
  const { data } = useExportsQuery({ page, limit: 10 }, { pollingInterval: 3000, skipPollingIfUnfocused: true });
  const filterText = (row: NonNullable<typeof data>['data'][number]) => [row.filters.location, row.filters.type, row.filters.from && `from ${row.filters.from}`, row.filters.to && `to ${row.filters.to}`].filter(Boolean).join(', ') || 'All records';
  const statusBadge = (status: 'PENDING' | 'COMPLETED' | 'FAILED') => status === 'COMPLETED' ? <span className="inline-flex items-center gap-1 rounded-full bg-green-50 px-2.5 py-1 text-xs font-semibold text-green-700"><CheckCircle2 size={14}/>Completed</span> : status === 'FAILED' ? <span className="inline-flex items-center gap-1 rounded-full bg-red-50 px-2.5 py-1 text-xs font-semibold text-red-700"><XCircle size={14}/>Failed</span> : <span className="inline-flex items-center gap-1 rounded-full bg-amber-50 px-2.5 py-1 text-xs font-semibold text-amber-700"><Clock3 className="animate-pulse" size={14}/>Pending</span>;
  return <><div className="mb-5"><h1 className="text-2xl font-bold text-maroon sm:text-3xl">Export History</h1><p className="mt-1 text-sm text-stone-500">Generate reports using the PDF and Excel buttons on the Statement page.</p></div>
    <div className="space-y-3 md:hidden">{data?.data.length ? data.data.map(row => <article className="card" key={row.id}><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><p className="font-bold text-maroon">{row.format}</p>{statusBadge(row.status)}</div><p className="mt-1 text-xs text-stone-500">{new Date(row.createdAt).toLocaleString('en-IN')}</p></div>{row.status === 'COMPLETED' && <a aria-label="Download report" className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-amber-50 text-maroon" href={`${apiUrl}/exports/${row.id}/download`}><Download/></a>}</div><p className="mt-3 break-words text-sm">{filterText(row)}</p><p className="mt-2 text-xs font-semibold text-stone-500">{row.status === 'COMPLETED' ? `${row.recordCount} transactions` : row.status === 'FAILED' ? row.errorMessage || 'Report generation failed' : 'The backend is generating your report…'}</p></article>) : <div className="card text-center text-stone-500">No reports generated yet. Go to Statement to create one.</div>}</div>
    <div className="card hidden overflow-x-auto p-0 md:block"><table className="w-full min-w-[700px]"><thead className="bg-amber-50 text-left"><tr><th className="p-4">Requested</th><th>Format</th><th>Status</th><th>Active filters</th><th>Records</th><th>Download</th></tr></thead><tbody>{data?.data.length ? data.data.map(row => <tr className="border-t border-amber-100" key={row.id}><td className="p-4">{new Date(row.createdAt).toLocaleString('en-IN')}</td><td>{row.format}</td><td>{statusBadge(row.status)}</td><td>{filterText(row)}</td><td>{row.status === 'COMPLETED' ? row.recordCount : '—'}</td><td>{row.status === 'COMPLETED' ? <a aria-label="Download report" className="inline-flex p-3 text-maroon" href={`${apiUrl}/exports/${row.id}/download`}><Download/></a> : <span className="text-sm text-stone-400">{row.status === 'FAILED' ? 'Unavailable' : 'Generating…'}</span>}</td></tr>) : <tr><td colSpan={6} className="p-8 text-center text-stone-500">No reports generated yet.</td></tr>}</tbody></table></div>
    {data && <div className="mt-4 flex flex-col items-center justify-between gap-3 rounded-xl border border-amber-100 bg-white p-3 sm:flex-row"><p className="text-sm text-stone-500">{data.pagination.total} exports · Page {data.pagination.page} of {data.pagination.pages}</p><div className="flex gap-2"><button className="btn-secondary min-h-11 px-4 py-2" disabled={data.pagination.page <= 1} onClick={() => setPage(current => current - 1)}>Previous</button><button className="btn-secondary min-h-11 px-4 py-2" disabled={data.pagination.page >= data.pagination.pages} onClick={() => setPage(current => current + 1)}>Next</button></div></div>}
  </>;
}
